version: '3.8'

services:
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
  frontend:
    image: frontend
    ports:
      - 5000:5000
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  database:  
