version: '3.8'

services:
    frontend:
      image: ml-kurkkumopo-frontend
      ports:
        - 3000:3000
    backend:
      image: ml-kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
      depends_on:
        - training
    training:
      image: ml-kurkkumopo-training
      volumes:
        - model:/src/model
        - imgs:/src/imgs

  volumes:
    model:
    imgs:    